name: NPM Publish

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      - name: Install Dependencies
        run: |
          echo "//registry.npmjs.org/:_authToken=${NODE_AUTH_TOKEN}" > .npmrc
          npm install

      - name: Publish to NPM
        run: |
          # Retry logic
          retries=3
          until [ $retries -le 0 ] || npm publish; do
            echo "Retrying npm publish..."
            sleep 10  # Tambahkan delay sebelum mencoba lagi
            ((retries--))
          done
        env:
          NODE_AUTH_TOKEN: ${{secrets.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}}
